### ISSUE TITLE
Error receiving post messages on /webhook

### ISSUE THREAD

**Issue by danfsd** [rickydunlop/fbmessenger-node#23]
Hi, I'm trying to setup for the first time my server with **fbmessenger**.
I've finished setting everything up on the App page:
- Webhook (`url` and `verify_token`) is listening for `messages`
- App is subscribed to a page
- `Page App Token` is correct

I'm getting the following error every time the page receives a message:

```
TypeError: Cannot read property 'entry' of undefined
    at Messenger.handle (/var/www/letsrock/clientes/sellia-messenger/node_modules/fbmessenger/dist/Messenger.js:106:26)
    at /var/www/letsrock/clientes/sellia-messenger/dist/index.js:46:13
    at Layer.handle [as handle_request] (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/var/www/letsrock/clientes/sellia-messenger/node_modules/express/lib/middleware/init.js:40:5)
```

Any ideas of what is going on?

**Edit**:
- `package.json`:
```
{
  "name": "sellia-messenger",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "rimraf dist/ && babel ./ --out-dir dist/ --ignore ./node_modules,./.babelrc,./package.json,./npm-debug.log --copy-files",
    "start": "npm run build && node dist/index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^4.0.0",
    "express": "^4.15.3",
    "fbmessenger": "^4.0.0",
    "socketio": "^1.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "rimraf": "^2.6.1"
  }
}
```

- `.babelrc`:
```
{
  "presets": ["es2015"]
}
```

Thanks

**Comment by rickydunlop** [comment]
Can you show me the code that you're using to listen for messages? It might be handy to share a `console.log` of the input here too.

Are you able to run any of the examples with your app token?

**Comment by danfsd** [comment]
I'm using the standard boilerplate code that you put on the `README.md`. Here it goes:

```js
import { Messenger } from 'fbmessenger';

var express = require('express');
var app = express();
require('dotenv').config();

// Initialize Messenger 
const messenger = new Messenger({
    pageAccessToken: '<Token Omitted>'
});

// here we define some listeners: 
messenger.on('message', (event) => {
    // put your logic here 
    console.log("received message, answering it");
    messenger.send({text: "Test Answer"}, event.sender.id);
});
 
messenger.on('postback', (event) => {
    // put your logic here 
    console.log("received postback");
});
 
// This example shows how to setup verification using express 
app.get('/webhook', (req, res) => {
    if (req.query['hub.mode'] === 'subscribe' &&
        req.query['hub.verify_token'] === process.env.VERIFY_TOKEN) {
        res.send(req.query['hub.challenge']);
    } else {
        res.sendStatus(400);
    }
});
 
 
// This route handles the webhook callbacks from Facebook 
app.post('/webhook', (req, res) => {
    res.sendStatus(200);
    messenger.handle(req.body);
});

app.get('/', (req, res) => {
    res.send('Hello World');
});

app.listen(3030, () => {
    console.log('Example app listening on port 3030!');
});

```

> Are you able to run any of the examples with your app token?

Didn't tried running the examples though. Will try it and then answer you.

>  It might be handy to share a console.log of the input here too.

What input? Are you referring to what comes on `req` on `POST /webhook` or on `on('message')` `event` variable?

**Comment by danfsd** [comment]
@rickydunlop the **example** worked as a charm.

Can you see anything wrong on my code that is preventing it from working?
I saw that on your **example** there's a moment where you ask for the `APP_SECRET` while on that **boilerplate code** (and on my own code) there is not a trace of `APP_SECRET` being asked/used.

**Comment by rickydunlop** [comment]
It might be that you need to add this `app.use(bodyParser.json());` as it looks like it's not reading the payload correctly.

`APP_SECRET` is used to verify the request signature from Facebook, you should use this to make sure that the request comes from Facebook and not someone else

**Comment by danfsd** [comment]
@rickydunlop it worked! 🎉 
Thanks for the assistance 😁

Do you think is reasonable to add the `body-parser` to the `README.md`'s code?

**Comment by rickydunlop** [comment]
Yes, please do. Open a PR.
Thanks!
